backend:
  name: git-gateway
  branch: main
media_folder: public/img
public_folder: img
collections:
  - name: "signs"
    label: "Signs"
    folder: "content/signs"
    create: true
    fields:
      - {label: "Sign", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown", required: false}